name: "Setup Git Config for GitHub App"
description: "Configure global git user settings for GitHub App"

inputs:
  token:
    description: "GitHub App token"
    required: true
  app-slug:
    description: "GitHub App slug"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get GitHub App User ID
      id: get-user-id
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        APP_SLUG: ${{ inputs.app-slug }}
      run: |
        USER_ID=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)
        echo "user-id=$USER_ID" >> $GITHUB_OUTPUT
        echo "GitHub App User ID: $USER_ID"
    
    - name: Setup global git config for GitHub App
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        APP_SLUG: ${{ inputs.app-slug }}
        USER_ID: ${{ steps.get-user-id.outputs.user-id }}
      run: |
        echo "GitHub App: $APP_SLUG (User ID: $USER_ID)"
        
        # Configure git to use the GitHub App token for authentication
        git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
        
        # Generate user name and email for the GitHub App
        USER_NAME="${APP_SLUG}[bot]"
        USER_EMAIL="${USER_ID}+${APP_SLUG}[bot]@users.noreply.github.com"
        
        # Set global git config
        git config --global user.name "$USER_NAME"
        git config --global user.email "$USER_EMAIL"
        
        echo "✅ Global git config set:"
        echo "   Name: $(git config --global user.name)"
        echo "   Email: $(git config --global user.email)"
        echo "   Authentication: Configured for GitHub App token"
