name: "Setup Git Config for GitHub App"
description: "Configure global git user settings for GitHub App"

inputs:
  app-id:
    description: "GitHub App ID"
    required: true
  app-slug:
    description: "GitHub App slug"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup global git config for GitHub App
      shell: bash
      env:
        APP_ID: ${{ inputs.app-id }}
        APP_SLUG: ${{ inputs.app-slug }}
      run: |
        echo "GitHub App: $APP_SLUG (ID: $APP_ID)"
        
        # Generate user name and email for the GitHub App
        USER_NAME="${APP_SLUG}[bot]"
        USER_EMAIL="${APP_ID}+${APP_SLUG}[bot]@users.noreply.github.com"
        
        # Set global git config
        git config --global user.name "$USER_NAME"
        git config --global user.email "$USER_EMAIL"
        
        echo "✅ Global git config set:"
        echo "   Name: $(git config --global user.name)"
        echo "   Email: $(git config --global user.email)"
