name: "Update PRs auto merge enabled"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions: {}

jobs:
  update-prs-auto-merge-enabled:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write # Required to update PRs
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          persist-credentials: false
      - uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app_token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update PRs by rebase
        uses: ./update-prs-auto-merge-enabled
        with:
          token: ${{ steps.app_token.outputs.token }}
          base_branch: main
          limits: 30

      - name: Update PRs by merge
        uses: ./update-prs-auto-merge-enabled
        with:
          token: ${{ steps.app_token.outputs.token }}
          base_branch: main
          limits: 30
          update_method: merge
