name: "Update PRs auto merge enabled action"

inputs:
  base_branch:
    description: "The base branch to compare the PRs"
    type: string
    required: true
  token:
    description: "The GitHub token has the permission to `pull-requests: write`"
    type: string
    required: true
  limits:
    description: "The limits for the number of PRs to update"
    type: number
    required: false
    default: 30

runs:
  using: "composite"
  steps:
    - name: update PRs auto merge enabled
      uses: actions/github-script@v7
      env:
        BASE_BRANCH: ${{ inputs.base_branch }}
        LIMITS: ${{ inputs.limits }}
      with:
        github-token: ${{ inputs.token }}
        script: |
          const script = require(process.env.GITHUB_ACTION_PATH + '/script.js');
          await script({github, context}).catch((error) => core.setFailed(error.message));
